import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
import { ExplanationProvider } from "@/context/explanation-context";
import { SidebarProvider } from "@/components/ui/sidebar";

const albertSans = Albert_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${albertSans.className} antialiased`}
      >
        <ExplanationProvider>
          <SidebarProvider>
            {children}
          </SidebarProvider>
        </ExplanationProvider>
      </body>
    </html>
  );
}
