import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
import { ExplanationProvider } from "@/context/explanation-context";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from 'react-hot-toast';
import { SessionProvider } from "next-auth/react";

const albertSans = Albert_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${albertSans.className} antialiased`}
      >
        <SessionProvider>
          <ExplanationProvider>
            <SidebarProvider>
              <Toaster />
              {children}
            </SidebarProvider>
          </ExplanationProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
